### PR TITLE
use post request for state changing actions

### PR DESCRIPTION
**Pull request by lalithr95**
Minor change use POST request for the DB state changing actions to prevent CSRF issues.

@jules2689

### CODE REVIEW

**Comment by jules2689** [comment]
🙅‍♂️ this will need to be put upstream, not to our fork. I'm not willing to merge this unless upstream will take this.

**Review by jules2689 — CHANGES_REQUESTED** [review]
Needs to go upstream

**Comment by lalithr95** [comment]
Sure, I'll open a PR upstream first.

**Comment by lalithr95** [comment]
Merged in upstream

**Comment by jules2689** [comment]
deployed

**Pull request closed without merging**
